# Generated by Django 3.1.5 on 2021-01-16 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0006_electioncandidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('party', models.CharField(max_length=32, null=True)),
                ('symbol', models.CharField(max_length=32, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(max_length=32, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electioncandidate_created_by', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.district')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electioncandidate_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.electioncandidate')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electionresult_created_by', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.district')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pollingstation',
            options={},
        ),
        migrations.DeleteModel(
            name='ElectionCandidates',
        ),
        migrations.AddField(
            model_name='electionresult',
            name='polling_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.pollingstation'),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electionresult_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
